name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release ${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc]
        cfg_release_channel: [stable]

    steps:
      - uses: actions/checkout@master
      - name: Apply target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build Project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Release Project
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .\target\${{ matrix.target }}\release\rs-top.exe